### ISSUE TITLE
Bio Romain améliorations?

### ISSUE THREAD

**Issue by Toskyll** [isolab-inc/projet-isolab#10]
### Salut, je me suis permis de lire vos bio et je te propose de changer quelques mots ou bien quelques formulation si jamais tu es d'accord. Si tout te paraît bien alors tu peux fermer l'issue.

Depuis mon enfance, j'ai toujours eu un vif intérêt pour l'univers du jeu vidéo <ins>, et plus tard de l'informatique, qui n'a cessé de se développer au fil des années</ins> _(->puis, en grandissant, c'est celui pour l'informatique qui n'a cessé de se développer)_. C'est au cours du confinement que j'ai touché pour la première fois à la programmation, et depuis il m'a ~~donc~~ toujours paru évident que la voie qui me conviendrait le mieux serait celle de l'informatique <ins>, pour faire de ma passion mon avenir, et c'est donc ce qui m'a poussé à prendre la spécialité NSI au lycée, puis à rejoindre l'EPITA, 
afin de développer mes compétences en informatique. </ins> _(->. C'est donc pour faire de ma passion mon avenir que j'ai choisi de prendre la spécialité NSI au lycée et ainsi intégrer l'EPITA)_
La pratique est selon moi le meilleur moyen d'apprendre, et ce projet entre ~~donc~~ totalement dans cette vision, et je pense donc pouvoir en tirer beaucoup d'expérience et d'acquérir de nouvelles compétences, aussi bien en informatique qu'en travail de groupe.

<h5>Si jamais tu trouves qu'il y a quelque chose à modifier que ce soit dans ta biographie ou la mienne, tu peux directement changer ta bio ou bien créer une issue pour me dire ce que je devrais changer.</h5>

**Comment by Dragons-3** [comment]
Ouais c'est mieux avec les modifs que tu proposes, je les ai mises sur overleaf
