### ISSUE TITLE
Bio Matteo améliorations?

### ISSUE THREAD

**Issue by Toskyll** [isolab-inc/projet-isolab#11]
### Salut, je me suis permis de lire vos bio et je te propose de changer quelques mots ou bien quelques formulation si jamais tu es d'accord. Si tout te paraît bien alors tu peux fermer l'issue.

Ma passion pour les jeux vidéo a débuté dès l'enfance avec des jeux comme <ins>pokemon</ins> _(->Pokémon)_ puis <ins>minecraft</ins> _(->Minecraft)_. Depuis lors, j'ai plongé dans un vaste éventail de jeux, explorant divers genres et univers. Pourtant, ce sont les jeux multijoueur compétitifs qui <ins>ont rapidement émergé comme</ins> _(->furent rapidement)_ mes préférés, suscitant un enthousiasme pour notre projet actuel. Initialement, j'avais envisagé de me diriger directement vers une carrière dans l'industrie du jeu vidéo. Cependant, au fil du temps, j'ai mûri ma réflexion et j'ai décidé de prendre une voie plus large <ins>et d'embrasser un champ d'études plus complet</ins> _(->avec un champ d'études plus complet)_. Cette décision m'a conduit à explorer tous les aspects de la programmation et de l'informatique en général, un domaine qui m'a toujours intrigué et passionné.

<h5>Si jamais tu trouves qu'il y a quelque chose à modifier que ce soit dans ta biographie ou la mienne, tu peux directement changer ta bio ou bien créer une issue pour me dire ce que je devrais changer.</h5>

**Comment by FireBlade60** [comment]
dsl j'ai pas check avant mais sa me vas merci

**Comment by Toskyll** [comment]
Fait les modifs dcp :)

**Comment by Toskyll** [comment]
J'ai fais les modifs
