### ISSUE TITLE
Bio Léon améliorations?

### ISSUE THREAD

**Issue by Toskyll** [isolab-inc/projet-isolab#12]
### Salut, je me suis permis de lire vos bio et je te propose de changer quelques mots ou bien quelques formulation si jamais tu es d'accord. Si tout te paraît bien alors tu peux fermer l'issue.

J'ai commencé la "programmation" en primaire avec Scratch car mon ambition était de devenir développeur de jeux vidéos,  j'ai continué mon apprentissage à travers des stages de formation afin d'apprendre à utiliser des moteurs comme Construct 2 au début du collège puis je me suis adonné au C\# vers la fin de mon collège en commen<ins>c</ins>ant _(ç)_ par Bolt puis par du C\# classique, notamment sur Unity à travers plusieurs formations qui m'ont fait découvrir la beauté des raycasts et des navmeshs.
En seconde j'ai réussi à obtenir une dérogation de la part de mon lycée afin <ins>de pouvoir participer à</ins> _(->de prendre)_ la spécialité NSI au CNED qui m'a fait reprend<ins>r</ins>e mon apprentissage des bases du python et du javascript. J'aime beaucoup les roguelikes, les boomer-shooters et les jeux rétros. Je suis très enjoué de pouvoir commencer ce projet avec un groupe qui a l'air d'avoir des attentes similaires aux miennes et qui parait bien organisé (pour le moment).

<h5>Si jamais tu trouves qu'il y a quelque chose à modifier que ce soit dans ta biographie ou la mienne, tu peux directement changer ta bio ou bien créer une issue pour me dire ce que je devrais changer.</h5>

**Comment by Dazzeuh** [comment]
Donc modifier a "afin de pouvoir prendre part à"?

**Comment by Toskyll** [comment]
Perso je pense tu peux juste ecrire "En seconde j'ai réussi à obtenir une dérogation de la part de mon lycée afin de prendre la spécialité NSI au CNED qui m'a fait reprendre mon apprentissage des bases du python et du javascript."

**Comment by Toskyll** [comment]
J'ai changé tt seul pour mettre en forme le Cdc
