### ISSUE TITLE
Bio Alexandre améliorations?

### ISSUE THREAD

**Issue by Toskyll** [isolab-inc/projet-isolab#13]
### Salut, je me suis permis de lire vos bio et je te propose de changer quelques mots ou bien quelques formulation si jamais tu es d'accord. Si tout te paraît bien alors tu peux fermer l'issue.

Depuis que j’ai eu mon premier contact avec les jeux-vidéos <ins>lors de mon enfance dans un premier lieu puis par celui d’internet</ins> _(->dans mon enfance puis par le biais d'internet)_, j’ai toujours été passionné par les jeux-vidéos. À commencer par Pokémon puis Minecraft, ce dernier m’a permis de développer une certaine créativité et m’a donc incité à créer. Je me suis tout d’abord essayé au dessin, puis au « graphisme », puis une fois <ins>mettre</ins> _(->m'ayant/m'être/que je me suis)_ procuré un ordinateur plus performant, je me suis mis à faire du montage vidéo<ins>, de</ins> _(->. De)_ plus cet ordinateur m’a permis de découvrir les jeux compétitifs qui sont _(devenus)_ mes préférés, ce qui <ins>sollicite</ins> _(accentue)_ encore plus mon engouement pour ce projet. Étant dans un lycée ne disposant pas ~~de~~ la spécialité NSI, j’ai donc décidé de la suivre au CNED. Suite à cela j’ai donc décidé de rejoindre EPITA pour m’offrir une voie disposant de nombreuses possibilités. N’ayant pas eu un apprentissage en programmation approfondit, j’apprends à EPITA et j’espère que ce projet en groupe me permettra aussi d’en apprendre beaucoup.

<h5>Si jamais tu trouves qu'il y a quelque chose à modifier que ce soit dans ta biographie ou la mienne, tu peux directement changer ta bio ou bien créer une issue pour me dire ce que je devrais changer.</h5>

**Comment by LeXouuu** [comment]
Modifications effectues.
