### ISSUE TITLE
Carte CDC

### ISSUE THREAD

**Issue by Toskyll** [isolab-inc/projet-isolab#14]
Ecris la partie technique pour la **carte** sur le cahier des charges.

**Comment by FireBlade60** [comment]
Description de la Carte:
Objectif du Projet:
Le but de ce projet est de créer une carte de jeu vidéo complexe, divisée en quatre parties symétriques pour un Battle Royale à 4 équipes(???). Les joueurs pourront s'affronter tout en chassant des monstres et collectant des ressources pour améliorer leurs personnages.

La carte doit être divisée en quatre parties équilibrées et symétriques
La carte devra inclure une variété d'environnements tels que des obstacles naturels et des zones de couverture.
Des bâtiments, des caches, et des éléments interactifs (pièges, portes, etc.) devront être répartis de manière équilibrée sur la carte.
Il devra y avoir des emplacements de spawn pour les joueurs, les monstres, et les ressources (armes, potions, etc.) qui seront répartis équitablement.

Éléments de Gameplay:

Les joueurs pourront chasser des monstres pour obtenir des récompenses (objets, équipement, etc.)
Les joueurs pourront collecter des ressources pour améliorer leurs personnages (fabrication d'objets, améliorations, etc.).
Le mode Battle Royale à 4 joueurs doit être pris en compte avec des mécaniques de survie, de zone de sécurité (fermeture de certaines partie de la carte au fur et a mesure)
La carte doit être conçue pour favoriser les interactions PvP tout en permettant aux joueurs d'explorer et d'interagir avec l'environnement.
