### ISSUE TITLE
Projet Unity

### ISSUE THREAD

**Issue by Toskyll** [isolab-inc/projet-isolab#22]
### Liste des taches à faire pour créer le projet Unity :

- [x] Choisir une version fixe d'éditeur pour Unity
- [x] Créer le projet et faire en sorte que tout le monde puisse setup son travail
- [x] Merge la branch unity-setup sur main #23 
- [x] Vérifier que tout le monde a bien le bon setup du projet

Les deux version LTS que j'ai pour l'instant vu et qui sont mises en avant sont :

- [Unity 2021.3.31](https://unity.com/releases/editor/whats-new/2021.3.31)
- [Unity 2022.3.11](https://unity.com/releases/editor/whats-new/2022.3.11)

**Comment by Toskyll** [comment]
Versions choisie : [2022.3.11](https://unity.com/releases/editor/whats-new/2022.3.11)

**Comment by Dazzeuh** [comment]
Banger
